# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# Upload the CSV file
print("Please, upload your CSV file.")
uploaded = files.upload()
csv_file = list(uploaded.keys())[0]
df = pd.read_csv(csv_file)

# Check the data content
print("Had of the dataset:")
print(df.head())
print("\nColumns:", df.columns.tolist())

# Clean the null data if there is any.
df = df[['PROBLEM_TYPE', 'no_of_cases']]
df = df.dropna()

# Count the problem types
summary = df.groupby('PROBLEM_TYPE')['no_of_cases'].sum().sort_values(ascending=False).reset_index()
summary.columns = ['PROBLEM_TYPE', 'no_of_cases']

#Show the problem which has the highest report
top_problem = summary.iloc[0]
print("\nMost reported problem:")
print(top_problem)

# Summary
print("\nSummary:")
print(f"This report identifies '{top_problem['PROBLEM_TYPE']}' as the most frequent customer complaint with {top_problem['no_of_cases']} cases.")

# Visualization
plt.figure(figsize=(10,6))
sns.barplot(data=summary.head(10), x='no_of_cases', y='PROBLEM_TYPE', palette='Reds_r')
plt.title('Top 10 Customer Complaint Types')
plt.xlabel('Number of Cases')
plt.ylabel('Problem Type')
plt.tight_layout()
plt.show()